#!/usr/bin/env python3
"""Maintain a scannable index at the top of decisions/log.md.

The decision log is append-only and each entry is a long single line
([DATE] DECISION: ... | REASONING: ... | CONTEXT: ...), so the file is ~95KB —
expensive to load whole just to see what was decided. This regenerates a compact
index block (date + decision headline, one line each) between INDEX markers at
the top, so an agent can survey every decision in ~1-2k tokens and jump to the
full entry it needs. vault_search covers full-text retrieval; this covers
at-a-glance scanning.

Idempotent: rewrites only the marked block, never the entries. Dry-run by
default; --apply writes.

Usage:
    python3 system/tools/decisions_index.py            # show the index it would write
    python3 system/tools/decisions_index.py --apply
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

LOG_REL = "decisions/log.md"
BEGIN = "<!-- INDEX:BEGIN (generated by decisions_index.py — do not edit by hand) -->"
END = "<!-- INDEX:END -->"
ENTRY_RE = re.compile(r"^\[(\d{4}-\d{2}-\d{2})\]\s*DECISION:\s*(.+?)(?:\s*\|\s*REASONING:|\s*$)", re.M)
HEADLINE_MAX = 130


def build_index(entries: list[tuple[str, str]]) -> str:
    lines = [BEGIN, "", "## Decision index", "",
             f"_{len(entries)} decisions, newest first. Full entries below._", ""]
    for date, headline in entries:
        h = headline.strip()
        if len(h) > HEADLINE_MAX:
            h = h[: HEADLINE_MAX - 1].rstrip() + "…"
        lines.append(f"- **{date}** — {h}")
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=".")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    log = root / LOG_REL
    text = log.read_text()

    # Strip any existing index block before scanning for entries.
    body = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n*", "", text, flags=re.S)
    entries = ENTRY_RE.findall(body)
    if not entries:
        print("No decision entries found (expected '[YYYY-MM-DD] DECISION: ...').")
        return 0

    index = build_index(entries)

    # Insert after the header preamble: keep everything up to and including the
    # first '---' separator, then index, then the rest of the body.
    sep = body.find("\n---\n")
    if sep != -1:
        head = body[: sep + len("\n---\n")]
        rest = body[sep + len("\n---\n"):]
        new_text = head + "\n" + index + "\n" + rest.lstrip("\n")
    else:
        new_text = index + "\n\n" + body

    if args.apply:
        log.write_text(new_text)
        print(f"Wrote index with {len(entries)} decisions to {LOG_REL}")
    else:
        print(index)
        print(f"\n(dry-run — {len(entries)} decisions; use --apply to write)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
